language: node_js
dist: trusty
sudo: required
node_js:
  - 6
branches:
  only:
  - gh-pages
before_install:
  # wine needs 32 bit architecture
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt-get install wine1.6
install:
  - npm install
script:
  - npm run pack
  - zip -r jwr-caw-linux-x64 jwr-caw-linux-x64/
  - zip -r jwr-caw-darwin-x64 jwr-caw-darwin-x64/
  - zip -r jwr-caw-win32-x64 jwr-caw-win32-x64/
deploy:
  skip_cleanup: true
  provider: releases
  file:
    - jwr-caw-linux-x64.zip
    - jwr-caw-darwin-x64.zip
    - jwr-caw-win32-x64.zip
  on:
    # tags: true
    repo: jwronline/caw
    branch: gh-pages
